### ISSUE TITLE
Feedback 12-03

### ISSUE THREAD

**Issue by sreen020** [ralfz123/CATCH-YOUR-LAUGH--PWA#1]
README
- Alle dingen van het vak zal ik lekker weghalen
- Duidelijke readme

CODE
- app.js bevat best veel regels miss kan je deze opsplitsen 
- Je kan je routes loskoppelen 

- Ik zie dat je node-fetch en request in je project heb zitten, ik denk dat er 1 wegkan

- Fetch.js en like.js staan nog veel comments in

- Mappenstructuur ziet er verzorgd uit!
- "Refactored code, but clienstide js is weird -_-" hahaha

**Comment by ralfz123** [comment]
Thanks Sjoerd!! Lekkere feedback, Ik ben ook zeker bezig met mijn project te optimaliseren. 

Thanks man!

🔥 🔥 🔥
