### ISSUE TITLE
Destructure arguments object for leaner code?

### ISSUE THREAD

**Issue by joostf** [ralfz123/CATCH-YOUR-LAUGH--PWA#3]
https://github.com/ralfz123/progressive-web-apps-2021/blob/4bbde742edbe9cc38cb22bfb2348280d2cfedb4c/views/pages/favourites.ejs#L20

**Comment by ralfz123** [comment]
Thanks for the feedback Joost! What do you mean with the arguments object? Can you explain it for me :)

🔥🔥🔥

**Comment by joostf** [comment]
You could write it like this:
``` javascript
        <% favouritesArray.forEach({cat, setup, punchline, id}}=> { %>
          <li>
            <img src="<%= cat %>" alt="" />
        ...
```

or

``` javascript
        <% favouritesArray.forEach(object)=> {
          const {cat, setup, punchline, id} = object
        %>
          <li>
            <img src="<%= cat %>" alt="" />
        ...
```
so you can write ```cat``` instead of ```object.cat```
