### ISSUE TITLE
.env.example maken

### ISSUE THREAD

**Issue by jochemvogel** [ralfz123/CATCH-YOUR-LAUGH--PWA#4]
Hoe je het noemt, maakt niet uit. Maar er is geen voorbeeld van de `.env` in de repo. Daarnaast staat er ook niets over in je README, dus als ik het lokaal werkend wil krijgen, weet ik niet hoe dat moet.

**Comment by ralfz123** [comment]
Thanks voor de feedback Jochem, maar ik gebruik in dit project geen .env of hidden files. :)
